---
abstract: 'a wrapper for AI::ANN'
author:
  - 'Dan Collins <dcollin1@stevens.edu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DCOLLINS-ANN-Locals
requires:
  AI::ANN: 0
  Inline::C: 0
  Math::Libm: 1.00
  Moose: 2.00
  Storable: 0
version: 0.004
